"""alter session table add isdeleted

Revision ID: b86dcdf62d66
Revises: fcba985ed88b
Create Date: 2025-02-11 14:05:15.213602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86dcdf62d66'
down_revision: Union[str, None] = 'fcba985ed88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'is_deleted')
    # ### end Alembic commands ###
