"""alter message table role

Revision ID: fcba985ed88b
Revises: 56dcb61be80e
Create Date: 2025-02-11 13:46:20.416406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcba985ed88b'
down_revision: Union[str, None] = '56dcb61be80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'role',
               existing_type=postgresql.ENUM('user', 'ai', name='chat_role'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('user', 'ai', name='chat_role'),
               existing_nullable=False)
    # ### end Alembic commands ###
