version: "3.9"

services:
  db:
    image: postgres:15
    container_name: sample_postgres
    restart: always

    # .envから環境変数を読み込む
    env_file:
      - ../.env

    # コンテナ内での PostgreSQL 環境変数を設定
    # => dbコンテナ内では POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB を使用
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: